Test for 1-my_list.py
-------------------------------------------

import:
>>> MyList = __import__('1-my_list').MyList

normal usage:
>>> my_list = MyList()
>>> my_list.append(1)
>>> my_list.append(4)
>>> my_list.append(2)
>>> print(my_list)
[1, 4, 2]
>>> my_list.print_sorted()
[1, 2, 4]

empty list:
>>> a = []
>>> my_list = MyList(a)
>>> my_list.print_sorted()
[]

defined list:
>>> a = [5, 1, 3]
>>> my_list = MyList(a)
>>> my_list.print_sorted()
[1, 3, 5]

list in order:
>>> a = [1, 2, 3]
>>> my_list = MyList(a)
>>> my_list.print_sorted()
[1, 2, 3]

same number:
>>> a = [1, 1, 1]
>>> my_list = MyList(a)
>>> my_list.print_sorted()
[1, 1, 1]

one number:
>>> a = [1]
>>> my_list = MyList(a)
>>> my_list.print_sorted()
[1]

object not defined:
>>> MyList = __import__('1-my_list').MyList
>>> my_list2.print_sorted()
Traceback (most recent call last):
NameError: name 'my_list2' is not defined
